# Generated by Django 4.0.4 on 2022-05-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicdir', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musicdir',
            options={'ordering': ['created_at'], 'verbose_name': 'Композиция', 'verbose_name_plural': 'Композиции'},
        ),
        migrations.AlterField(
            model_name='musicdir',
            name='content',
            field=models.TextField(blank=True, verbose_name='Трек'),
        ),
        migrations.AlterField(
            model_name='musicdir',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время публикации'),
        ),
        migrations.AlterField(
            model_name='musicdir',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Трек опубликован?'),
        ),
        migrations.AlterField(
            model_name='musicdir',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='musicdir',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='musicdir',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее обновление'),
        ),
    ]
